### ISSUE TITLE
@conda-forge-admin, please add user @gadomski

### ISSUE THREAD

**Issue by gadomski** [conda-forge/stac-check-feedstock#4]
### Additional comment:

I'm a owner of the [stac-utils](https://github.com/stac-utils) and would like to be able to modify/approve PRs on this feedstock.

**Comment by jonhealy1** [comment]
I agree

**Comment by gadomski** [comment]
@jonhealy1 can you do this yourself, manually, on this repo? Seems like the bot didn't hear me (or I did it wrong).

**Comment by jonhealy1** [comment]
@gadomski I don't see the settings tab in this repo? Is there another way?

**Comment by jonhealy1** [comment]
@gadomski I can approve the 1.3.2 pr - I guess i should do this

**Comment by gadomski** [comment]
Looks like my second attempt worked, can you approve this one too? https://github.com/conda-forge/stac-check-feedstock/pull/6
